"""Generate the command-line reference pages from src/data/flags.json + src/data/flag-notes.json.

Usage: python3 scripts/gen-flag-docs.py
Writes src/content/docs/docs/reference/flags.mdoc and deprecated-flags.mdoc (generated; don't edit them by hand).
Warns about flags without notes and notes for flags that no longer exist, so a new release shows what to write.
"""

import json
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
data = json.loads((root / "src/data/flags.json").read_text())
notes = json.loads((root / "src/data/flag-notes.json").read_text())
out_dir = root / "src/content/docs/docs/reference"
version = data["version"]
flags = data["flags"]

dests = {f["dest"] for f in flags}
for f in flags:
    if f["dest"] not in notes:
        print(f"warning: no note for {f['flags'][0]}")
for dest in notes.keys() - dests:
    print(f"warning: note for a flag that no longer exists: {dest}")


def esc(text):
    """Escape Markdown/Markdoc syntax in text that comes from koboldcpp.py."""
    return re.sub(r"([\\`*_\[\]{}<>|#])", r"\\\1", text)


def anchor(f):
    return next(o for o in f["flags"] if o.startswith("--")).lstrip("-")


def value_of(f):
    if f["action"] in ("store_true", "store_false"):
        return None
    if f["metavar"]:
        return f["metavar"] if isinstance(f["metavar"], str) else " ".join(f["metavar"])
    if f["choices"]:
        return " | ".join(str(c) for c in f["choices"])
    return f["type"] or "value"


def facts(f, note):
    parts = []
    aliases = [o for o in f["flags"] if o != "--" + anchor(f)]
    if aliases:
        parts.append("Also: " + ", ".join(f"`{a}`" for a in aliases))
    value = value_of(f)
    if value:
        parts.append(f"Value: `{value}`")
    if f["default"] not in (None, False, "", []) and f["action"] != "store_true":
        parts.append(f"Default: `{f['default']}`")
    if note.get("launcher"):
        parts.append(f"Launcher: {note['launcher']}")
    return " · ".join(parts)


def entry(f):
    note = notes.get(f["dest"], {})
    lines = [f"### `--{anchor(f)}` {{% #{anchor(f)} %}}", ""]
    meta = facts(f, note)
    if meta:
        lines += [meta, ""]
    if note.get("summary"):
        lines += [note["summary"], ""]
    if note.get("details"):
        lines += [note["details"], ""]
    if note.get("replacedBy"):
        lines += [f"Use instead: {note['replacedBy']}", ""]
    if f["help"]:
        lines += [f"> Help text: {esc(f['help'])}", ""]
    return lines


def page(title, description, order, intro, sections, label=None):
    body = ["---", f'title: "{title}"', f"description: {description}", "sidebar:",
            *([f'  label: "{label}"'] if label else []), f"  order: {order}",
            "tableOfContents:", "  maxHeadingLevel: 2",
            f"# Generated by scripts/gen-flag-docs.py from koboldcpp.py {version}. Don't edit by hand.", "---", ""]
    body += intro + [""]
    for heading, items in sections:
        body += [f"## {heading}", ""]
        for f in items:
            body += entry(f)
    return "\n".join(body).rstrip() + "\n"


public = [f for f in flags if not f["hidden"]]
deprecated = [f for f in flags if f["hidden"] and f["group"] != "Internal Commands"]

group_names = {"General": "Basics", "Advanced Commands": "Advanced"}
sections = {}
for f in public:
    name = group_names.get(f["group"], f["group"].removesuffix(" Commands"))
    sections.setdefault(name, []).append(f)

beginner = [f for f in public if notes.get(f["dest"], {}).get("level") == "beginner"]
intro = [
    f"Every flag KoboldCpp {version} accepts, generated from its source code. Run `koboldcpp --help` to see the same list in a terminal.",
    "",
    "Flags go after the file name, for example `koboldcpp.exe --model mymodel.gguf --contextsize 8192`. "
    "Most flags also exist in the launcher; each entry names the tab and label.",
    "",
    "## Most used",
    "",
    "| Flag | What it does |",
    "| --- | --- |",
    *[f"| [`--{anchor(f)}`](#{anchor(f)}) | {notes[f['dest']]['summary']} |" for f in beginner],
]
(out_dir).mkdir(parents=True, exist_ok=True)
(out_dir / "flags.mdoc").write_text(page(
    "Command-line flags and options reference",
    f"Every KoboldCpp command-line flag with what it does, its default and its launcher setting. Generated from KoboldCpp {version}.",
    1, intro, sections.items(), label="Command-line flags"))

dep_intro = [
    "These flags are hidden from `--help`. They still parse so that old commands and `.kcpps` files keep working; "
    "some still have an effect, others are ignored. Use the replacement listed for each.",
]
(out_dir / "deprecated-flags.mdoc").write_text(page(
    "Deprecated flags",
    f"Old KoboldCpp flags, what replaced them and whether they still do anything. Generated from KoboldCpp {version}.",
    2, dep_intro, [("Deprecated", deprecated)]))
print(f"wrote {len(public)} flags, {len(deprecated)} deprecated, {len(beginner)} in 'Most used'")
